name: Go Devcontainer Example
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Podman
        uses: parkan/github-actions/setup-podman-docker@v1
        
      - name: Test in Devcontainer
        uses: parkan/github-actions/devcontainer-test@v1
        with:
          test-command: 'go version && go test -v ./...'
          container-runtime: podman
